name: hydraedge-ci

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install -e .[dev]   # dev extras contain pytest,jsonschema,ruff
      - run: pytest -q
  schema-lint:
    runs-on: ubuntu-latest
    steps:
      …  # call validate_json.py on datasets/*.jsonl
