name: Smoke
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
jobs:
  smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.11'}
    - run: pip install .
    - run: scripts/build_tiny_index.py
    - run: pytest tests/smoke -q
    - run: docker build -t linker:test -f docker/Dockerfile .
    - run: docker run -d -p 8000:80 --name linker linker:test &&
           sleep 5 &&
           docker exec linker /app/src/serve/healthcheck.sh
